// <auto-generated />
using System;
using BehindArt.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BehindArt.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BehindArt.Domain.Entitiyes.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("int");

                    b.Property<int?>("DeathYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "Italian polymath of the High Renaissance.",
                            BirthYear = 1452,
                            DeathYear = 1519,
                            Name = "Leonardo da Vinci"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "Dutch post-impressionist painter.",
                            BirthYear = 1853,
                            DeathYear = 1890,
                            Name = "Vincent van Gogh"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "Norwegian expressionist painter.",
                            BirthYear = 1863,
                            DeathYear = 1944,
                            Name = "Edvard Munch"
                        });
                });

            modelBuilder.Entity("BehindArt.Domain.Entitiyes.Era", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EndYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StartYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Eras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A period of cultural rebirth in Europe.",
                            EndYear = 1600,
                            Name = "Renaissance",
                            StartYear = 1300
                        },
                        new
                        {
                            Id = 2,
                            Description = "Emphasis on symbolic content and geometric form.",
                            EndYear = 1905,
                            Name = "Post-Impressionism",
                            StartYear = 1886
                        },
                        new
                        {
                            Id = 3,
                            Description = "Art that presents the world from a subjective perspective.",
                            EndYear = 1933,
                            Name = "Expressionism",
                            StartYear = 1905
                        });
                });

            modelBuilder.Entity("BehindArt.Domain.Entitiyes.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("PaintingId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaintingId");

                    b.HasIndex("UserId", "PaintingId")
                        .IsUnique();

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("BehindArt.Domain.Entitiyes.Painting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EraId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Story")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Views")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("EraId");

                    b.ToTable("Paintings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 1,
                            CreatedAt = new DateTime(2026, 8, 19, 13, 2, 50, 716, DateTimeKind.Utc).AddTicks(1702),
                            Description = "Portrait of a woman with an enigmatic expression.",
                            EraId = 1,
                            ImageUrl = "https://placehold.co/600x800?text=Mona+Lisa",
                            Title = "Mona Lisa",
                            Views = 0,
                            Year = 1503
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 2,
                            CreatedAt = new DateTime(2026, 8, 19, 13, 2, 50, 716, DateTimeKind.Utc).AddTicks(1713),
                            Description = "A swirling night sky over a quiet village.",
                            EraId = 2,
                            ImageUrl = "https://placehold.co/600x800?text=Starry+Night",
                            Title = "The Starry Night",
                            Views = 0,
                            Year = 1889
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 3,
                            CreatedAt = new DateTime(2026, 8, 19, 13, 2, 50, 716, DateTimeKind.Utc).AddTicks(1716),
                            Description = "An agonized figure against a blood-red sky.",
                            EraId = 3,
                            ImageUrl = "https://placehold.co/600x800?text=The+Scream",
                            Title = "The Scream",
                            Views = 0,
                            Year = 1893
                        },
                        new
                        {
                            Id = 4,
                            ArtistId = 1,
                            CreatedAt = new DateTime(2026, 8, 19, 13, 2, 50, 716, DateTimeKind.Utc).AddTicks(1718),
                            Description = "Melting clocks in a dreamlike landscape.",
                            EraId = 1,
                            ImageUrl = "https://placehold.co/600x800?text=Persistence+of+Memory",
                            Title = "The Persistence of Memory",
                            Views = 0,
                            Year = 1931
                        },
                        new
                        {
                            Id = 5,
                            ArtistId = 2,
                            CreatedAt = new DateTime(2026, 8, 19, 13, 2, 50, 716, DateTimeKind.Utc).AddTicks(1720),
                            Description = "A young girl wearing an exotic dress and a pearl earring.",
                            EraId = 2,
                            ImageUrl = "https://placehold.co/600x800?text=Girl+with+Pearl+Earring",
                            Title = "Girl with a Pearl Earring",
                            Views = 0,
                            Year = 1665
                        });
                });

            modelBuilder.Entity("BehindArt.Domain.Entitiyes.Save", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("PaintingId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaintingId");

                    b.HasIndex("UserId", "PaintingId")
                        .IsUnique();

                    b.ToTable("Saves");
                });

            modelBuilder.Entity("BehindArt.Domain.Entitiyes.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BehindArt.Domain.Entitiyes.Like", b =>
                {
                    b.HasOne("BehindArt.Domain.Entitiyes.Painting", "Painting")
                        .WithMany("Likes")
                        .HasForeignKey("PaintingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BehindArt.Domain.Entitiyes.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Painting");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BehindArt.Domain.Entitiyes.Painting", b =>
                {
                    b.HasOne("BehindArt.Domain.Entitiyes.Artist", "Artist")
                        .WithMany("Paintings")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BehindArt.Domain.Entitiyes.Era", "Era")
                        .WithMany("Paintings")
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Era");
                });

            modelBuilder.Entity("BehindArt.Domain.Entitiyes.Save", b =>
                {
                    b.HasOne("BehindArt.Domain.Entitiyes.Painting", "Painting")
                        .WithMany("Saves")
                        .HasForeignKey("PaintingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BehindArt.Domain.Entitiyes.User", "User")
                        .WithMany("Saves")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Painting");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BehindArt.Domain.Entitiyes.Artist", b =>
                {
                    b.Navigation("Paintings");
                });

            modelBuilder.Entity("BehindArt.Domain.Entitiyes.Era", b =>
                {
                    b.Navigation("Paintings");
                });

            modelBuilder.Entity("BehindArt.Domain.Entitiyes.Painting", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("Saves");
                });

            modelBuilder.Entity("BehindArt.Domain.Entitiyes.User", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("Saves");
                });
#pragma warning restore 612, 618
        }
    }
}
